import React, { useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import '../utils/i18n';
import useAuth from '../utils/hooks/index';
import { useDispatch } from 'react-redux';
import { addMessage } from '../store/slices/chatSlice';

const Home = () => {
  const router = useRouter();
  const auth = useAuth();
  useEffect(() => {
    console.log(auth);
    if (!auth.loggedIn) {
      router.push('/login');
    } else {
      router.push('/home');
    }
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Redirecting</p>
      </main>
    </>
  );
};

export default Home;